export default {
    GET_USER: "GET_USER",
    ADD_USER: "ADD_USER",
    UPDATE_USER: "UPDATE_USER",
    UPDATE_INPUT: "UPDATE_INPUT",
    GET_INPUT: "GET_INPUT",
    UPDATE_NAME: "SET_NAME",
    GET_NAME: "GET_NAME",
    UPDATE_UID: "SET_UID",
    GET_UID: "GET_UID",
    UPDATE_ZIP: "UPDATE_ZIP",
    UPDATE_CITY: "UPDATE_CITY",
    UPDATE_STATE: "UPDATE_STATE",
    REMOVE: "REMOVE",
    CHANGE_EVENT: "change",
    ADD_CLUB: "ADD_CLUB"
}